# Generated by Django 4.0.1 on 2022-01-08 04:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('japanese_name', models.CharField(max_length=32)),
                ('generation', models.IntegerField(null=True)),
                ('classification', models.CharField(max_length=64)),
                ('is_legendary', models.BooleanField()),
                ('abilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('type_1', models.CharField(max_length=16)),
                ('type_2', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'pokemon',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.IntegerField()),
                ('special_atk', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_def', models.IntegerField()),
                ('hit_points', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('speed', models.IntegerField()),
                ('capture_rate', models.FloatField()),
                ('pokedex_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_api.pokemon')),
            ],
            options={
                'verbose_name_plural': 'stats',
            },
        ),
        migrations.CreateModel(
            name='Multiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('against_bug', models.FloatField()),
                ('against_dark', models.FloatField()),
                ('against_dragon', models.FloatField()),
                ('against_electric', models.FloatField()),
                ('against_fairy', models.FloatField()),
                ('against_fight', models.FloatField()),
                ('against_fire', models.FloatField()),
                ('against_flying', models.FloatField()),
                ('against_ghost', models.FloatField()),
                ('against_grass', models.FloatField()),
                ('against_ground', models.FloatField()),
                ('against_ice', models.FloatField()),
                ('against_normal', models.FloatField()),
                ('against_poison', models.FloatField()),
                ('against_psychic', models.FloatField()),
                ('against_rock', models.FloatField()),
                ('against_steel', models.FloatField()),
                ('against_water', models.FloatField()),
                ('pokedex_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_api.pokemon')),
            ],
            options={
                'verbose_name_plural': 'multipliers',
            },
        ),
    ]
