# Generated by Django 4.0.1 on 2022-01-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplier',
            name='mult_id',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='stat_id',
        ),
        migrations.AddField(
            model_name='multiplier',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
