# Generated by Django 4.0.1 on 2022-01-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0002_alter_pokemon_pokedex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
