# Generated by Django 4.0.1 on 2022-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0002_alter_multiplier_against_bug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='is_legendary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stat',
            name='attack',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stat',
            name='defense',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stat',
            name='hit_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stat',
            name='special_atk',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stat',
            name='special_def',
            field=models.IntegerField(default=1),
        ),
    ]
