# Generated by Django 4.0.1 on 2022-01-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0004_alter_pokemon_pokedex_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipliers',
            old_name='mult_id',
            new_name='pokedex_id',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='stat_id',
            new_name='pokedex_id',
        ),
    ]
