# Generated by Django 4.0.1 on 2022-04-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multiplier',
            unique_together={('pokedex_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='pokemon',
            unique_together={('pokedex_id', 'name', 'japanese_name')},
        ),
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together={('pokedex_id',)},
        ),
    ]
