# Generated by Django 4.0.1 on 2022-01-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=16)),
                ('mname', models.CharField(blank=True, max_length=16, null=True)),
                ('lname', models.CharField(max_length=16)),
                ('date_of_birth', models.DateField(default='1992-01-01')),
                ('rank', models.CharField(choices=[('Prof.', 'Professor'), ('Asst. Prof.', 'Assistant Professor'), ('Asc. Prof.', 'Associate Professor'), ('Lec.', 'Lecturer')], max_length=64)),
                ('date_of_joining', models.DateField(default='2017-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('grant_body', models.CharField(max_length=256)),
                ('grant_body_url', models.URLField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=16)),
                ('mname', models.CharField(blank=True, max_length=16, null=True)),
                ('lname', models.CharField(max_length=16)),
                ('date_of_birth', models.DateField(default='1992-01-01')),
                ('degree', models.CharField(max_length=32)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('period', models.CharField(choices=[('Monthly', 'monthly'), ('Quarterly', 'quarterly'), ('Bi-Annually', 'biannually'), ('Annually', 'annually')], max_length=32)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.scholarshipscheme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_pay', models.IntegerField()),
                ('conveyance_allowance', models.IntegerField()),
                ('house_rent_allowance', models.IntegerField()),
                ('medical_allowance', models.IntegerField()),
                ('special_allowance', models.IntegerField()),
                ('tax_deduction', models.DecimalField(decimal_places=2, max_digits=16)),
                ('pf_deduction', models.DecimalField(decimal_places=2, max_digits=16)),
                ('medical_insurance', models.IntegerField()),
                ('take_home', models.DecimalField(decimal_places=2, max_digits=16)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.academian')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('dean', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.academian')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.academian'),
        ),
    ]
