# Generated by Django 4.0.1 on 2022-01-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Diploma', 'Dip.'), ('Post Graduate Diploma', 'PGD.'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Master of Philosophy', 'MPhil.'), ('Doctor of Philosophy', 'PhD')], max_length=128)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.faculty')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.degree'),
        ),
    ]
