# Generated by Django 4.0.1 on 2022-01-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_student_degree_awarded_degree_alter_student_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academian',
            name='date_of_joining',
            field=models.DateField(default='2015-08-01'),
        ),
    ]
